version: '3'
services:
  web:
    build: .
    command: rails s -b 0.0.0.0 -p 5000
    # container_name: economias_sso
    ports:
      - 5000:5000
    volumes:
      - .:/economias
    links:
      - db
    env_file: .env  

  db:
    image: postgres:12-alpine
    volumes:
      - economias_data:/var/lib/postgresql/data
    env_file: .env 
  
volumes:
  economias_data: