
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch['POSTGRES_HOST'] %> 
  username: <%= ENV.fetch['POSTGRES_USER'] %>
  password: <%= ENV.fetch['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: economias_app_development

test:
  <<: *default
  database: economias_app_test

production:
  <<: *default
  database: economias_app_production
  username: economias_app
  password: <%= ENV['ECONOMIAS_APP_DATABASE_PASSWORD'] %>
