default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: postgres
  port: 5432

development:
  <<: *default
  database: economias_app_development

test:
  <<: *default
  database: economias_app_test

production:
  <<: *default
  database: economias_app_production
  username: postgres
  password: postgres